import{S as f,i as a}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const d="44262674-4191f931eb8b9eeb7747e3c1c";function m(n){const r="https://pixabay.com",o="/api/",i=new URLSearchParams({key:d,q:n,image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${r}${o}?${i}`;return fetch(e).then(t=>{if(!t.ok)throw new Error(`HTTP error! status: ${t.status}`);return t.json()})}const u=document.querySelector(".gallery"),l=document.querySelector(".div-loader");l.style.display="none";let h=new f(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});function y(n){return n.map(({largeImageURL:r,tags:o,webformatURL:i,likes:e,views:t,comments:s,downloads:p})=>`
              <a href="${r}" class="gallery-item">
                <img src="${i}" alt="${o}" loading="lazy">
                <div class="info">
                  <p><b>Likes:</b> ${e}</p>
                  <p><b>Views:</b> ${t}</p>
                  <p><b>Comments:</b> ${s}</p>
                  <p><b>Downloads:</b> ${p}</p>
                </div>
              </a>
          `).join("")}function g(){l.style.display="block"}function c(){setTimeout(()=>{l.style.display="none"},2e3)}const b=document.querySelector(".form");b.addEventListener("submit",n=>{n.preventDefault(),u.innerHTML="";const r=n.target.elements.searchQuery.value;if(!r.length){a.error({title:"Error",message:'"Sorry, input is empty"',position:"topRight"});return}g(),m(r).then(o=>{if(!o.hits.length){a.error({title:"Error",message:'"Sorry, there are no images matching your search query. Please try again!"',position:"topRight"}),c();return}const i=y(o.hits);u.innerHTML=i,h.refresh(),c()}).catch(o=>{a.error({title:"Error",message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),c(),console.error("Error fetching pictures:",o)})});
//# sourceMappingURL=commonHelpers.js.map
